name: homehelper
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  flutter_secure_storage: ^3.3.1+1
  hydrated_bloc: ^3.0.0

  # Interface components
  assorted_layout_widgets: ^1.0.15
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.2
  dotted_border: ^1.0.5
  dynamic_theme: ^1.0.1
  flare_flutter: ^2.0.1
  flutter_map: ^0.8.2
  flutter_rating_bar: ^3.0.1+1
  flutter_slidable: ^0.5.4
  font_awesome_flutter: ^8.7.0
  percent_indicator: ^2.1.1+1
  qr_flutter: ^3.2.0
  qr_mobile_vision: ^0.3.1
  reorderables: ^0.3.2

dev_dependencies:
  effective_dart: ^1.2.1
  flutter_test:
    sdk: flutter

  # File generation
  build_runner: ^1.8.0
  copy_with_extension_gen: ^1.0.8
  json_serializable: ^3.2.5

flutter:

  uses-material-design: true